import extractarticle

openArticle1dhl = open("courier_text/dhl1.txt", encoding="utf8")
openArticle2dhl = open("courier_text/dhl2.txt", encoding="utf8")
openArticle3dhl = open("courier_text/dhl3.txt", encoding="utf8")
openArticle1poslaju = open("courier_text/poslaju1.txt", encoding="utf8")
openArticle2poslaju = open("courier_text/poslaju2.txt", encoding="utf8")
openArticle3poslaju= open("courier_text/poslaju3.txt", encoding="utf8")
openArticle1jnt = open("courier_text/j&t1.txt", encoding="utf8")
openArticle2jnt = open("courier_text/j&t2.txt", encoding="utf8")
openArticle3jnt = open("courier_text/j&t3.txt", encoding="utf8")
openArticle1gdex = open("courier_text/gdex1.txt", encoding="utf8")
openArticle2gdex = open("courier_text/gdex2.txt", encoding="utf8")
openArticle3gdex = open("courier_text/gdex3.txt", encoding="utf8")
openArticle1citylink = open("courier_text/citylink1.txt", encoding="utf8")
openArticle2citylink = open("courier_text/citylink2.txt", encoding="utf8")
openArticle3citylink = open("courier_text/citylink3.txt", encoding="utf8")

# openArticle1dhl = open("dhl1.txt")
# openArticle2dhl = open("dhl2.txt")
# openArticle3dhl = open("dhl3.txt")
# openArticle1poslaju = open("poslaju1.txt")
# openArticle2poslaju = open("poslaju2.txt")
# openArticle3poslaju= open("poslaju3.txt")
# openArticle1jnt = open("j&t1.txt")
# openArticle2jnt = open("j&t2.txt")
# openArticle3jnt = open("j&t3.txt")
# openArticle1gdex = open("gdex1.txt")
# openArticle2gdex = open("gdex2.txt")
# openArticle3gdex = open("gdex3.txt")
# openArticle1citylink = open("citylink1.txt")
# openArticle2citylink = open("citylink2.txt")
# openArticle3citylink = open("citylink3.txt")

readArticle1dhl = openArticle1dhl.read()
readArticle2dhl = openArticle2dhl.read()
readArticle3dhl = openArticle3dhl.read()
readArticle1poslaju = openArticle1poslaju.read()
readArticle2poslaju = openArticle2poslaju.read()
readArticle3poslaju = openArticle3poslaju.read()
readArticle1jnt = openArticle1jnt.read()
readArticle2jnt = openArticle2jnt.read()
readArticle3jnt = openArticle3jnt.read()
readArticle1gdex = openArticle1gdex.read()
readArticle2gdex = openArticle2gdex.read()
readArticle3gdex = openArticle3gdex.read()
readArticle1citylink = openArticle1citylink.read()
readArticle2citylink = openArticle2citylink.read()
readArticle3citylink = openArticle3citylink.read()

wordListdhl = readArticle1dhl.split() + readArticle2dhl.split() + readArticle3dhl.split()
wordListposlaju = readArticle1poslaju.split() + readArticle2poslaju.split() + readArticle3poslaju.split()
wordListjnt = readArticle1jnt.split() + readArticle2jnt.split() + readArticle3jnt.split()
wordListgdex = readArticle1gdex.split() + readArticle2gdex.split() + readArticle3gdex.split()
wordListcitylink = readArticle1citylink.split() + readArticle2citylink.split() + readArticle3citylink.split()

wordListNoStopWordsdhl = extractarticle.removeStopwords(wordListdhl, extractarticle.stopwords)
positiveWordListdhl = extractarticle.inPositive(wordListNoStopWordsdhl, extractarticle.PositiveWord)
negativeWordListdhl = extractarticle.inNegative(wordListNoStopWordsdhl, extractarticle.NegativeWord)
wordListNoStopWordsposlaju = extractarticle.removeStopwords(wordListposlaju, extractarticle.stopwords)
positiveWordListposlaju = extractarticle.inPositive(wordListNoStopWordsposlaju, extractarticle.PositiveWord)
negativeWordListposlaju = extractarticle.inNegative(wordListNoStopWordsposlaju, extractarticle.NegativeWord)
wordListNoStopWordsjnt = extractarticle.removeStopwords(wordListjnt, extractarticle.stopwords)
positiveWordListjnt = extractarticle.inPositive(wordListNoStopWordsjnt, extractarticle.PositiveWord)
negativeWordListjnt = extractarticle.inNegative(wordListNoStopWordsjnt, extractarticle.NegativeWord)
wordListNoStopWordsgdex = extractarticle.removeStopwords(wordListgdex, extractarticle.stopwords)
positiveWordListgdex = extractarticle.inPositive(wordListNoStopWordsgdex, extractarticle.PositiveWord)
negativeWordListgdex = extractarticle.inNegative(wordListNoStopWordsgdex, extractarticle.NegativeWord)
wordListNoStopWordscitylink = extractarticle.removeStopwords(wordListcitylink, extractarticle.stopwords)
positiveWordListcitylink = extractarticle.inPositive(wordListNoStopWordscitylink, extractarticle.PositiveWord)
negativeWordListcitylink = extractarticle.inNegative(wordListNoStopWordscitylink, extractarticle.NegativeWord)
dictionarydhl = extractarticle.wordListToFreqDict(wordListNoStopWordsdhl)
sorteddictdhl = extractarticle.sortFreqDict(dictionarydhl)
dictionaryposlaju = extractarticle.wordListToFreqDict(wordListNoStopWordsposlaju)
sorteddictposlaju = extractarticle.sortFreqDict(dictionaryposlaju)
dictionaryjnt = extractarticle.wordListToFreqDict(wordListNoStopWordsjnt)
sorteddictjnt = extractarticle.sortFreqDict(dictionaryjnt)
dictionarygdex = extractarticle.wordListToFreqDict(wordListNoStopWordsgdex)
sorteddictgdex = extractarticle.sortFreqDict(dictionarygdex)
dictionarycitylink = extractarticle.wordListToFreqDict(wordListNoStopWordscitylink)
sorteddictcitylink = extractarticle.sortFreqDict(dictionarycitylink)

# display word and frequency
print("Words and its count for DHL:")
for t in sorteddictdhl: print(str(t))
print()

print("Words and its count for PosLaju:")
for t in sorteddictposlaju: print(str(t))
print()

print("Words and its count for J&T:")
for t in sorteddictjnt: print(str(t))
print()

print("Words and its count for GDex:")
for t in sorteddictgdex: print(str(t))
print()

print("Words and its count for CityLink:")
for t in sorteddictcitylink: print(str(t))
print()